version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - openolat

  olat:
    image: tomcat:9-jdk11
    restart: always
    environment:
      - CATALINA_OPTS=-Ddb.host=${DB_HOST} -Ddb.port=${DB_PORT} -Ddb.name=${DB_NAME} -Ddb.user=${DB_USER} -Ddb.pass=${DB_PASS} -Duser.timezone=Europe/Berlin -Dspring.profiles.active=myprofile -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=.
    volumes:
      - ./openolat/openolat_${OLAT_VERSION}:/opt/openolat/webapp
      - ./themes/impavit:/opt/openolat/webapp/static/themes/impavit
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
      - ./tomcat/olat.local.properties:/usr/local/tomcat/lib/olat.local.properties
      - ./data/olatdata:/opt/openolat/olatdata
    networks:
      - openolat
    depends_on:
      - db

  athena:
    image: arachnysdocker/athenapdf-service
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      WEAVER_AUTH_KEY: ${ATHENA_SECRET}
      WEAVER_ATHENA_CMD: athenapdf -S --ignore-gpu-blacklist
      WEAVER_MAX_WORKERS: 10
      WEAVER_MAX_CONVERSION_QUEUE: 50
      WEAVER_WORKER_TIMEOUT: 90
      WEAVER_CONVERSION_FALLBACK: "false"
      GIN_MODE: debug
    networks:
      - openolat

  nginx:
    restart: always
    image: nginx:latest
    environment:
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    networks:
      - openolat

networks:
  openolat:
    driver: bridge